function Write-ADPostureDashboardData {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $DashboardData,
        [string]$SerializedJson
    )

    $cfg = Get-ModuleConfig
    $json = $SerializedJson
    if ([string]::IsNullOrWhiteSpace($json)) {
        Write-Host '  Building compressed latest dashboard JSON...'
        $json = $DashboardData | ConvertTo-Json -Depth 12 -Compress
    }

    $reportsLatest = Join-Path $cfg.ReportPath 'latest-dashboard.json'
    $dashboardLatest = Join-Path $cfg.DashboardPath 'latest-dashboard.json'
    $dashboardJs = Join-Path $cfg.DashboardPath 'dashboard-data.js'

    if (-not (Test-Path $cfg.ReportPath)) {
        New-Item -ItemType Directory -Path $cfg.ReportPath -Force -ErrorAction Stop | Out-Null
    }

    Write-Host '  Writing latest dashboard JSON files...'
    Write-ADPostureAtomicTextFile -Path $reportsLatest -Value $json
    Write-ADPostureAtomicTextFile -Path $dashboardLatest -Value $json
    Protect-ADPostureSensitiveFile -Path $reportsLatest
    Protect-ADPostureSensitiveFile -Path $dashboardLatest
    Write-ADPostureDashboardStore -DashboardData $DashboardData -StorePath (Join-Path $cfg.ReportPath 'dashboard-store')

    $js = @"
/* Generated by AD Posture - do not edit.
   Classification: Sensitive AD posture data. Do not publish or commit. */
window.__AD_AUDIT_DATA__ = $json;
"@
    Write-Host '  Writing latest dashboard JavaScript data file...'
    Write-ADPostureAtomicTextFile -Path $dashboardJs -Value $js
    Protect-ADPostureSensitiveFile -Path $dashboardJs
}

function Write-ADPostureDashboardStore {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $DashboardData,
        [Parameter(Mandatory)]
        [string]$StorePath
    )

    if (-not (Test-Path -LiteralPath $StorePath)) {
        New-Item -ItemType Directory -Path $StorePath -Force -ErrorAction Stop | Out-Null
    }

    $collectionNames = @(
        'findings', 'monitoring', 'exceptions', 'groups',
        'objects', 'objectEvidence', 'objectRelationships',
        'aclFindings', 'gpos', 'gpoLinks', 'gpoFindings',
        'adcsTemplates', 'adcsCas', 'adcsFindings',
        'kerberosAuthPrincipals', 'kerberosAuthFindings',
        'trusts', 'trustFindings', 'dnsZones', 'dnsRecords', 'dnsAdmins', 'dnsFindings',
        'identityRiskFindings'
    )
    $manifestCollections = [ordered]@{}
    foreach ($name in $collectionNames) {
        $items = if ($DashboardData -is [System.Collections.IDictionary] -and $DashboardData.Contains($name)) {
            @($DashboardData[$name])
        }
        elseif ($DashboardData.PSObject.Properties[$name]) {
            @($DashboardData.$name)
        }
        else {
            @()
        }
        $fileName = "$name.json"
        $path = Join-Path $StorePath $fileName
        Write-ADPostureAtomicTextFile -Path $path -Value ($items | ConvertTo-Json -Depth 12 -Compress)
        Protect-ADPostureSensitiveFile -Path $path
        $manifestCollections[$name] = [ordered]@{ file = $fileName; count = @($items).Count }
    }

    $meta = if ($DashboardData -is [System.Collections.IDictionary]) { $DashboardData['meta'] } else { $DashboardData.meta }
    $adcsNtAuth = if ($DashboardData -is [System.Collections.IDictionary]) { $DashboardData['adcsNtAuth'] } else { $DashboardData.adcsNtAuth }
    $kerberosAuthPolicy = if ($DashboardData -is [System.Collections.IDictionary]) { $DashboardData['kerberosAuthPolicy'] } else { $DashboardData.kerberosAuthPolicy }
    $manifest = [ordered]@{
        version = 2
        generatedAt = (Get-Date).ToString('o')
        meta = $meta
        singletons = [ordered]@{
            adcsNtAuth = $adcsNtAuth
            kerberosAuthPolicy = $kerberosAuthPolicy
        }
        collections = $manifestCollections
    }
    $manifestPath = Join-Path $StorePath 'manifest.json'
    Write-ADPostureAtomicTextFile -Path $manifestPath -Value ($manifest | ConvertTo-Json -Depth 12 -Compress)
    Protect-ADPostureSensitiveFile -Path $manifestPath
}

function Write-ADPostureTimelineDashboardData {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $TimelineData
    )

    $cfg = Get-ModuleConfig
    Write-Host '  Building compressed timeline dashboard JSON...'
    $json = $TimelineData | ConvertTo-Json -Depth 12 -Compress

    $reportsPath = Join-Path $cfg.ReportPath 'timeline-comparison.json'
    $dashboardJson = Join-Path $cfg.DashboardPath 'timeline-comparison.json'
    $dashboardJs = Join-Path $cfg.DashboardPath 'timeline-data.js'

    Write-Host '  Writing timeline dashboard JSON files...'
    Write-ADPostureAtomicTextFile -Path $reportsPath -Value $json
    Write-ADPostureAtomicTextFile -Path $dashboardJson -Value $json
    Protect-ADPostureSensitiveFile -Path $reportsPath
    Protect-ADPostureSensitiveFile -Path $dashboardJson

    $js = @"
/* Generated by AD Posture - do not edit.
   Classification: Sensitive AD posture data. Do not publish or commit. */
window.__AD_TIMELINE_DATA__ = $json;
"@
    Write-Host '  Writing timeline dashboard JavaScript data file...'
    Write-ADPostureAtomicTextFile -Path $dashboardJs -Value $js
    Protect-ADPostureSensitiveFile -Path $dashboardJs
}

function Get-ADPostureAclFieldClassification {
    [ordered]@{
        TargetName = 'Sensitive'
        TargetDistinguishedName = 'Sensitive'
        TargetCanonicalName = 'Sensitive'
        TargetObjectSid = 'Sensitive'
        TrusteeName = 'Sensitive'
        TrusteeSid = 'Sensitive'
        TrusteeDistinguishedName = 'Sensitive'
        RawTrustee = 'Sensitive'
        OwnerName = 'Sensitive'
        OwnerSid = 'Sensitive'
        OwnerDistinguishedName = 'Sensitive'
        SourceDescriptorId = 'Sensitive'
        RawSddl = 'Sensitive'
        Sddl = 'Sensitive'
        RawSecurityDescriptor = 'Sensitive'
        SecurityDescriptorSddl = 'Sensitive'
        NormalizedRight = 'Operational'
        RiskScore = 'Operational'
        Severity = 'Operational'
        ObjectTypeName = 'Operational'
        Remediation = 'Operational'
    }
}

function Copy-ADPostureRedactedAclRow {
    param(
        [Parameter(Mandatory)]
        $Row
    )

    $redactedFields = @(
        'TargetName',
        'TargetDistinguishedName',
        'TargetCanonicalName',
        'TargetObjectSid',
        'TargetObjectGuid',
        'TrusteeName',
        'TrusteeSid',
        'TrusteeDistinguishedName',
        'RawTrustee',
        'OwnerName',
        'OwnerSid',
        'OwnerDistinguishedName',
        'SourceDescriptorId',
        'RawSddl',
        'Sddl',
        'RawSecurityDescriptor',
        'SecurityDescriptorSddl',
        'RelatedObjectName',
        'Path'
    )

    $copy = [ordered]@{}
    foreach ($property in $Row.PSObject.Properties) {
        $copy[$property.Name] = if ($redactedFields -contains $property.Name) { '[REDACTED]' } else { $property.Value }
    }

    [pscustomobject]$copy
}

function Copy-ADPostureDashboardAclRow {
    param(
        [Parameter(Mandatory)]
        $Row,
        [int]$EffectiveTrusteeSampleSize = 10
    )

    $copy = [ordered]@{}
    foreach ($property in $Row.PSObject.Properties) {
        if ($property.Name -in @('EffectiveTrustees', 'EffectiveMembers')) { continue }
        $copy[$property.Name] = $property.Value
    }

    $effectiveTrustees = @()
    foreach ($propertyName in @('EffectiveTrustees', 'EffectiveMembers')) {
        if ($Row.PSObject.Properties[$propertyName] -and $Row.$propertyName) {
            $effectiveTrustees += @($Row.$propertyName)
        }
    }

    $copy['EffectiveTrusteeCount'] = @($effectiveTrustees).Count
    if ($effectiveTrustees.Count -gt 0) {
        $copy['EffectiveTrusteesSample'] = @($effectiveTrustees |
            Select-Object -First $EffectiveTrusteeSampleSize |
            ForEach-Object {
                [pscustomobject]@{
                    Name = if ($_.Name) { [string]$_.Name } elseif ($_.SamAccountName) { [string]$_.SamAccountName } else { 'Unknown effective trustee' }
                    Sid = if ($_.Sid) { [string]$_.Sid } elseif ($_.ObjectSid) { [string]$_.ObjectSid } else { $null }
                    DistinguishedName = if ($_.DistinguishedName) { [string]$_.DistinguishedName } else { $null }
                    ObjectClass = if ($_.ObjectClass) { [string]$_.ObjectClass } elseif ($_.AccountType) { [string]$_.AccountType } else { $null }
                    NestingDepth = if ($null -ne $_.NestingDepth) { [int]$_.NestingDepth } else { $null }
                    Path = if ($_.Path) { [string]$_.Path } else { $null }
                }
            })
        $copy['EffectiveTrusteesTruncated'] = ($effectiveTrustees.Count -gt $EffectiveTrusteeSampleSize)
    }

    [pscustomobject]$copy
}

function Get-ADPostureDashboardPayload {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $Snapshot,
        [switch]$RedactSensitiveAclEvidence
    )

    $aclFindings = @($Snapshot.AclFindings | ForEach-Object { Copy-ADPostureDashboardAclRow -Row $_ })
    $objectEvidence = @($Snapshot.ObjectEvidence)
    if ($RedactSensitiveAclEvidence) {
        $aclFindings = @($aclFindings | ForEach-Object { Copy-ADPostureRedactedAclRow -Row $_ })
        $objectEvidence = @($objectEvidence | ForEach-Object {
            if ($_.SourceDomain -eq 'ACL' -or $_.AclFindingId) { Copy-ADPostureRedactedAclRow -Row $_ } else { $_ }
        })
    }

    $approvedExceptions = @(
        @($Snapshot.Findings) + @($Snapshot.AclFindings) + @($Snapshot.GpoFindings) + @($Snapshot.AdcsFindings) + @($Snapshot.KerberosAuthFindings) + @($Snapshot.TrustFindings) + @($Snapshot.DnsFindings) + @($Snapshot.IdentityRiskFindings) |
            Where-Object { $_.IsApprovedException }
    )

    @{
        meta = @{
            sensitivity      = 'Sensitive - contains AD posture topology, DNs, SIDs, account metadata, and remediation context'
            aclFieldClassification = Get-ADPostureAclFieldClassification
            redactedAclEvidence = [bool]$RedactSensitiveAclEvidence
            domain           = $Snapshot.Domain
            forest           = $Snapshot.Forest
            timestamp        = $Snapshot.Timestamp
            overallRiskScore = $Snapshot.OverallRiskScore
            targetScore      = $Snapshot.TargetScore
            actionableCount  = $Snapshot.ActionableCount
            approvedExceptionCount = $Snapshot.ApprovedExceptionCount
            expiredExceptionCount = $Snapshot.ExpiredExceptionCount
            readiness       = $Snapshot.ReadinessScorecard
            remediation      = $Snapshot.RemediationBreakdown
            tierBreakdown    = $Snapshot.TierBreakdown
        }
        groups   = @($Snapshot.GroupSummaries)
        findings = @($Snapshot.Findings | Where-Object { -not $_.IsExcluded })
        aclFindings = @($aclFindings)
        gpos = @($Snapshot.Gpos)
        gpoLinks = @($Snapshot.GpoLinks)
        gpoFindings = @($Snapshot.GpoFindings)
        adcsTemplates = @($Snapshot.AdcsTemplates)
        adcsCas = @($Snapshot.AdcsCas)
        adcsNtAuth = $Snapshot.AdcsNtAuth
        adcsFindings = @($Snapshot.AdcsFindings)
        kerberosAuthPrincipals = @($Snapshot.KerberosAuthPrincipals)
        kerberosAuthPolicy = $Snapshot.KerberosAuthPolicy
        kerberosAuthFindings = @($Snapshot.KerberosAuthFindings)
        trusts = @($Snapshot.Trusts)
        trustFindings = @($Snapshot.TrustFindings)
        dnsZones = @($Snapshot.DnsZones)
        dnsRecords = @($Snapshot.DnsRecords)
        dnsAdmins = @($Snapshot.DnsAdmins)
        dnsFindings = @($Snapshot.DnsFindings)
        identityRiskFindings = @($Snapshot.IdentityRiskFindings)
        monitoring = @($Snapshot.Findings | Where-Object { $_.IsExcluded -and -not $_.IsApprovedException })
        exceptions = @($approvedExceptions)
        objects = @($Snapshot.Objects)
        objectEvidence = @($objectEvidence)
        objectRelationships = @($Snapshot.ObjectRelationships)
    }
}
