# Static dashboard writer. This overrides the retired split-store writer loaded earlier in module import order.
function Write-ADPostureDashboardData {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $DashboardData,
        [string]$SerializedJson
    )

    $cfg = Get-ModuleConfig
    $json = $SerializedJson
    if ([string]::IsNullOrWhiteSpace($json)) {
        Write-Host '  Building compressed latest dashboard JSON...'
        $json = $DashboardData | ConvertTo-Json -Depth 12 -Compress
    }

    $reportsLatest = Join-Path $cfg.ReportPath 'latest-dashboard.json'
    $dashboardLatest = Join-Path $cfg.DashboardPath 'latest-dashboard.json'
    $dashboardJs = Join-Path $cfg.DashboardPath 'dashboard-data.js'

    if (-not (Test-Path $cfg.ReportPath)) {
        New-Item -ItemType Directory -Path $cfg.ReportPath -Force -ErrorAction Stop | Out-Null
    }

    Write-Host '  Writing latest dashboard JSON files...'
    Write-ADPostureAtomicTextFile -Path $reportsLatest -Value $json
    Write-ADPostureAtomicTextFile -Path $dashboardLatest -Value $json
    Protect-ADPostureSensitiveFile -Path $reportsLatest
    Protect-ADPostureSensitiveFile -Path $dashboardLatest

    $js = @"
/* Generated by AD Posture - do not edit.
   Classification: Sensitive AD posture data. Do not publish or commit. */
window.__AD_AUDIT_DATA__ = $json;
"@
    Write-Host '  Writing latest dashboard JavaScript data file...'
    Write-ADPostureAtomicTextFile -Path $dashboardJs -Value $js
    Protect-ADPostureSensitiveFile -Path $dashboardJs
}

Remove-Item Function:\Write-ADPostureDashboardStore -Force -ErrorAction SilentlyContinue
