function New-ADPostureRemediationScript {
    <#
    .SYNOPSIS
    Generates a review-ready PowerShell script that removes a proven direct member from a sensitive group.
    .PARAMETER RemovalGroupIdentity
    The proven direct parent group to remove the member from. Defaults to the sensitive group itself.
    .PARAMETER WhatIfOnly
    Generates the script with -WhatIf for safe review only.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$SensitiveGroup,
        [Parameter(Mandatory)]
        [string]$MemberSamAccountName,
        [string]$RemovalGroupIdentity,
        [string]$Server,
        [switch]$WhatIfOnly,
        [string]$OutputPath
    )

    Test-ADModuleAvailable
    $cfg = Get-ModuleConfig
    if (-not $OutputPath) {
        $OutputPath = Join-Path $cfg.ReportPath "remediate-$(Get-Date -Format 'yyyyMMdd-HHmmss').ps1"
    }
    if ([string]::IsNullOrWhiteSpace($RemovalGroupIdentity)) {
        $RemovalGroupIdentity = $SensitiveGroup
    }

    $safeMember = ConvertTo-ADPosturePowerShellLiteral -Value $MemberSamAccountName
    $safeGroup = ConvertTo-ADPosturePowerShellLiteral -Value $SensitiveGroup
    $safeRemovalGroup = ConvertTo-ADPosturePowerShellLiteral -Value $RemovalGroupIdentity
    $safeServer = ConvertTo-ADPosturePowerShellLiteral -Value $Server
    $whatIf = if ($WhatIfOnly) { '-WhatIf' } else { '# Confirm before running without -WhatIf' }

    $script = @"
#Requires -Modules ActiveDirectory
# Generated by AD Posture - $(Get-Date -Format 'o')
# Classification: Sensitive - contains privileged AD remediation context.
# Action: remove a direct member from the proven parent group after approved change control.
# Review in a test environment. Run with -WhatIf first.

`$ErrorActionPreference = 'Stop'
Import-Module ActiveDirectory

function ConvertTo-ADFilterLiteral {
    param([AllowNull()][string]`$Value)
    if (`$null -eq `$Value) { return '' }
    return `$Value.Replace("'", "''")
}

`$MemberSamAccountName = $safeMember
`$SensitiveGroup = $safeGroup
`$RemovalGroupIdentity = $safeRemovalGroup
`$Server = $safeServer
`$serverParams = @{}
if (`$Server) { `$serverParams['Server'] = `$Server }

`$memberFilter = "SamAccountName -eq '`$(ConvertTo-ADFilterLiteral `$MemberSamAccountName)'"
`$member = Get-ADUser -Filter `$memberFilter @serverParams -ErrorAction SilentlyContinue
if (-not `$member) { `$member = Get-ADServiceAccount -Filter `$memberFilter @serverParams -ErrorAction SilentlyContinue }
if (-not `$member) { `$member = Get-ADComputer -Filter `$memberFilter @serverParams -ErrorAction SilentlyContinue }
if (-not `$member) { `$member = Get-ADGroup -Filter `$memberFilter @serverParams -ErrorAction SilentlyContinue }
if (-not `$member) { throw "Member not found: `$MemberSamAccountName" }

`$group = Get-ADGroup -Identity `$RemovalGroupIdentity -Properties member @serverParams -ErrorAction Stop
if (-not (@(`$group.member) -contains `$member.DistinguishedName)) {
    throw "Safety check failed: `$MemberSamAccountName is not a direct member of `$RemovalGroupIdentity. No change was made."
}
Remove-ADGroupMember -Identity `$group.DistinguishedName -Members `$member.DistinguishedName -Confirm:`$true $whatIf

Write-Host "Remediation requested for `$MemberSamAccountName -> `$RemovalGroupIdentity (sensitive path: `$SensitiveGroup)" -ForegroundColor Cyan
"@

    Set-Content -Path $OutputPath -Value $script -Encoding UTF8 -ErrorAction Stop
    Write-Host "Script generated: $OutputPath"
    return $OutputPath
}
