function Open-ADPostureDashboard {
    [CmdletBinding()]
    param(
        [ValidateSet('Current', 'ObjectRisk', 'AdcsPosture', 'KerberosAuthPosture', 'TrustPosture', 'DnsPosture', 'AclPosture', 'GpoPosture', 'Exceptions', 'Timeline', 'Executive')]
        [string]$View = 'Current',
        [string]$ReportDirectory
    )

    $cfg = Get-ModuleConfig
    $customReportDirectory = -not [string]::IsNullOrWhiteSpace($ReportDirectory)
    if (-not $ReportDirectory) { $ReportDirectory = $cfg.ReportPath }
    Write-Warning "Dashboards contain sensitive AD posture data. Open only on trusted workstations and avoid publishing generated dashboard JSON/JS files."

    Sync-ADPostureDashboardStaticAssets -SourcePath $cfg.DashboardSourcePath -TargetPath $cfg.DashboardPath

    $page = switch ($View) {
        'Exceptions' { 'exceptions.html' }
        'ObjectRisk' { 'objects.html' }
        'AdcsPosture' { 'adcs.html' }
        'KerberosAuthPosture' { 'auth.html' }
        'TrustPosture' { 'trusts.html' }
        'DnsPosture' { 'dns.html' }
        'AclPosture' { 'acl.html' }
        'GpoPosture' { 'gpo.html' }
        'Timeline'  { 'timeline.html' }
        'Executive' { 'executive.html' }
        default     { 'index.html' }
    }

    $htmlPath = Join-Path $cfg.DashboardPath $page
    if (-not (Test-Path -LiteralPath $htmlPath)) {
        throw "Dashboard not found: $htmlPath"
    }

    if ($View -eq 'Timeline') {
        $timelineJson = Join-Path $ReportDirectory 'timeline-comparison.json'
        $timelineJs = Join-Path $cfg.DashboardPath 'timeline-data.js'
        if ($customReportDirectory -or (Test-ADPostureDashboardDataRefreshRequired -SourcePath $timelineJson -ScriptPath $timelineJs)) {
            Write-ADPostureEmbeddedDashboardData -SourcePath $timelineJson -ScriptPath $timelineJs -VariableName '__AD_TIMELINE_DATA__'
        }
    }
    else {
        $latestJson = Join-Path $ReportDirectory 'latest-dashboard.json'
        if (-not (Test-Path -LiteralPath $latestJson)) {
            throw "Dashboard report not found: $latestJson"
        }

        $dashboardJs = Join-Path $cfg.DashboardPath 'dashboard-data.js'
        if ($customReportDirectory -or (Test-ADPostureDashboardDataRefreshRequired -SourcePath $latestJson -ScriptPath $dashboardJs)) {
            Write-ADPostureEmbeddedDashboardData -SourcePath $latestJson -ScriptPath $dashboardJs -VariableName '__AD_AUDIT_DATA__'
        }
    }

    Start-Process $htmlPath
}

function Sync-ADPostureDashboardStaticAssets {
    param(
        [AllowNull()][AllowEmptyString()]
        [string]$SourcePath,
        [AllowNull()][AllowEmptyString()]
        [string]$TargetPath
    )

    if ([string]::IsNullOrWhiteSpace($SourcePath) -or [string]::IsNullOrWhiteSpace($TargetPath)) { return }
    if ([System.IO.Path]::GetFullPath($SourcePath).TrimEnd('\') -eq [System.IO.Path]::GetFullPath($TargetPath).TrimEnd('\')) { return }
    if (-not (Test-Path -LiteralPath $SourcePath -PathType Container)) { return }

    if (-not (Test-Path -LiteralPath $TargetPath)) {
        New-Item -ItemType Directory -Path $TargetPath -Force -ErrorAction Stop | Out-Null
    }

    # Generated bundles are produced per environment and must never be copied from the module folder.
    $generatedNames = @('dashboard-data.js', 'timeline-data.js', 'latest-dashboard.json', 'timeline-comparison.json')
    foreach ($file in @(Get-ChildItem -LiteralPath $SourcePath -File -ErrorAction Stop | Where-Object { $_.Name -notin $generatedNames })) {
        $destination = Join-Path $TargetPath $file.Name
        if (-not (Test-Path -LiteralPath $destination) -or (Get-Item -LiteralPath $destination).LastWriteTimeUtc -lt $file.LastWriteTimeUtc) {
            Copy-Item -LiteralPath $file.FullName -Destination $destination -Force -ErrorAction Stop
        }
    }
}

function Test-ADPostureDashboardDataRefreshRequired {
    param(
        [Parameter(Mandatory)]
        [string]$SourcePath,
        [Parameter(Mandatory)]
        [string]$ScriptPath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) { return $false }
    if (-not (Test-Path -LiteralPath $ScriptPath)) { return $true }
    (Get-Item -LiteralPath $ScriptPath).LastWriteTimeUtc -lt (Get-Item -LiteralPath $SourcePath).LastWriteTimeUtc
}

function Write-ADPostureEmbeddedDashboardData {
    param(
        [Parameter(Mandatory)]
        [string]$SourcePath,
        [Parameter(Mandatory)]
        [string]$ScriptPath,
        [Parameter(Mandatory)]
        [string]$VariableName
    )

    $json = Get-Content -LiteralPath $SourcePath -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($json)) {
        throw "Dashboard report is empty: $SourcePath"
    }

    $script = "/* Generated by AD Posture - do not edit.`r`n   Classification: Sensitive AD posture data. Do not publish or commit. */`r`nwindow.$VariableName = $json;`r`n"
    Write-ADPostureAtomicTextFile -Path $ScriptPath -Value $script
    Protect-ADPostureSensitiveFile -Path $ScriptPath
}
